name: pr-ci-build
run-name: Build system for webapp during PR
on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr-ci-build:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: mysql
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_DATABASE: ${{ vars.DB_DATABASE }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASS: ${{ vars.DB_PASS }}
      PROF_TABLES: ${{ vars.PROF_TABLES }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: create tmp env file
        run: |
          ls -al
          touch .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
          echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_USER=${{ vars.DB_USER }}" >> .env
          echo "DB_PASS=${{ vars.DB_PASS }}" >> .env
          echo "PROF_TABLES=${{ vars.PROF_TABLES }}" >> .env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install

      - name: Setup mariadb action
        uses: ankane/setup-mariadb@v1
        with:
          database: webapp
      
      - name: Show database
        run: mysql -e 'SHOW DATABASES;'
        
      - name: set root user DB password
        run: mysql -D mysql -e "ALTER USER '${{ vars.DB_USER }}'@'${{ vars.DB_DATABASE }}' IDENTIFIED BY '${{ vars.DB_USER }}'";

      - name: flush privileges
        run: mysql -D mysql -e "flush privileges";

      - name: Start Express.js Server
        run: |
          npm run ci

      - uses: matt-ball/newman-action@master
        with:
          collection: tests/integration-tests/CSYE-webapp.postman_collection.json
